# Generated by Django 3.0.3 on 2020-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=30)),
                ('passport_number', models.CharField(max_length=30)),
                ('date_of_end', models.DateField()),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
