# Generated by Django 3.0.3 on 2020-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_passportdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportdata',
            name='gender',
        ),
        migrations.AddField(
            model_name='passportdata',
            name='status',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=2),
        ),
    ]
