# Generated by Django 3.0.3 on 2020-04-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200408_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportdata',
            name='status',
        ),
    ]
