# Generated by Django 3.0.3 on 2020-04-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_passportdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportdata',
            name='userid',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=2),
            preserve_default=False,
        ),
    ]
