# Generated by Django 3.0.3 on 2020-04-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_passportdata_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uniccode',
            field=models.CharField(default='111', max_length=50),
            preserve_default=False,
        ),
    ]
