# Generated by Django 3.0.3 on 2020-04-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_book_uniccode'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='adult',
            field=models.DecimalField(decimal_places=0, default='1', max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='child',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isic',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='senior',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=2),
            preserve_default=False,
        ),
    ]
