# Generated by Django 3.0.3 on 2020-04-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200420_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='adult',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='child',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='isic',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='senior',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2),
        ),
    ]
