# Generated by Django 3.0.3 on 2020-04-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200425_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='time_travel',
            field=models.TimeField(default='10:00'),
            preserve_default=False,
        ),
    ]
