# Generated by Django 3.0.3 on 2020-04-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_bus_time_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code_Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='bus_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='busid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='nos',
        ),
        migrations.RemoveField(
            model_name='book',
            name='source',
        ),
        migrations.RemoveField(
            model_name='book',
            name='time',
        ),
        migrations.AddField(
            model_name='book',
            name='bus',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Bus'),
        ),
        migrations.AddField(
            model_name='bus',
            name='dest_code',
            field=models.CharField(default='0', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='source_code',
            field=models.CharField(default='0', max_length=4),
            preserve_default=False,
        ),
    ]
