# Generated by Django 3.0.3 on 2020-04-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200429_0319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code_Name',
        ),
    ]
