# Generated by Django 3.0.3 on 2020-04-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_delete_code_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
