# Generated by Django 3.0.3 on 2020-05-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20200518_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='status',
            field=models.CharField(choices=[('A', 'Adult'), ('I', 'Isic'), ('CH', 'Child'), ('S', 'Senior')], default='A', max_length=2),
        ),
    ]
