# Generated by Django 3.0.3 on 2020-05-19 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_passenger_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='passenger',
        ),
        migrations.AddField(
            model_name='passenger',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.Book'),
        ),
    ]
